apiVersion: v1
kind: Service
metadata:
  name: package-service 
  namespace: saga-shipping
  labels:
    app: package-service 
spec:
  type: ClusterIP 
  selector:
    app: package-service 
  ports:
  - name: http
    protocol: TCP
    port: 5003        
    targetPort: 5003  