apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service 
  namespace: saga-shipping
  labels:
    app: customer-service # <-- CAMBIAR
spec:
  replicas: 1 # Puedes empezar con 1
  selector:
    matchLabels:
      app: customer-service # <-- CAMBIAR
  template:
    metadata:
      labels:
        app: customer-service # <-- CAMBIAR
    spec:
      containers:
      - name: customer-service-container # <-- CAMBIAR
        image: customer-service:latest # <-- CAMBIAR (usa tu imagen)
        imagePullPolicy: IfNotPresent # Ideal para desarrollo con Minikube
        ports:
        - containerPort: 5010 # <-- CAMBIAR
          name: http
        env:
        - name: SERVICE_NAME
          value: "customer-service" # <-- CAMBIAR
        - name: SERVICE_PORT
          value: "5010" # <-- CAMBIAR
        # Opcional: Para servicios que simulan fallos
        # - name: FAILURE_RATE
        #   value: "0.3" 
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health # Endpoint de chequeo
            port: 5010 # <-- CAMBIAR
          initialDelaySeconds: 15
          periodSeconds: 20