apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: saga-shipping
  labels:
    app: warehouse-service
spec:
  type: ClusterIP
  selector:
    app: warehouse-service
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001